// Generates supabase/seed.sql from src/data/events.json so the sample data
// used by the prototype and the real database never drift apart.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const events = JSON.parse(readFileSync(join(root, "src/data/events.json"), "utf8"));

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const arr = (a) => "ARRAY[" + a.map(q).join(",") + "]::event_category[]";
const txtArr = (a) => "ARRAY[" + a.map(q).join(",") + "]::text[]";

const rows = events.map((e) => {
  const itin = JSON.stringify(e.itinerary).replace(/'/g, "''");
  return `(${q(e.id)}, ${q(e.title)}, ${q(e.organizer)}, ${q(e.description)},
    ${arr(e.category)}, ${q(e.startsAt)}::timestamptz, ${q(e.endsAt)}::timestamptz,
    ${q(e.venueName)}, ${q(e.address)},
    ST_MakePoint(${e.lng}, ${e.lat})::geography,
    ${q(e.heroEmoji)}, ${txtArr(e.gradient)}, ${q(e.priceLabel)},
    ${q(e.rsvpUrl)}, ${q(e.sourceUrl)}, '${itin}'::jsonb, ${e.featured})`;
});

const sql = `-- AUTO-GENERATED by scripts/gen-seed.mjs — do not edit by hand.
-- Seeds ${events.length} sample heritage events.
truncate events cascade;
insert into events
  (slug, title, organizer, description, categories, starts_at, ends_at,
   venue_name, address, location, hero_emoji, gradient, price_label,
   rsvp_url, source_url, itinerary, featured)
values
${rows.join(",\n")};
`;

writeFileSync(join(root, "supabase/seed.sql"), sql);
console.log(`Wrote supabase/seed.sql with ${events.length} events.`);
